name: Deploy

on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

# Oa de Python setup had ik nu achterwege kunnen laten, omdat deze inmiddels is geïnstalleerd. 
# Ik heb die er nu voor de volledigheid bij laten staan.
      - name: Setup Python
        uses: actions/setup-python@v2

        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  send-files-to-vps:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
                  bash ~/bash_scripts/update.sh
   
