name: Deploy

on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: pytest

  send-files-to-vps:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
                  bash ~/bash_scripts/update.sh
   
